spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
logging:
  level:
    root: info
    com.renxuan.blog: debug
  file:
    path: log/blog-dev.log
